// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "ExtensibleObjectJsonHandler.h"
#include "IntegerJsonHandler.h"

namespace CesiumGltf {
  struct AccessorSparseValues;

  class AccessorSparseValuesJsonHandler final : public ExtensibleObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, AccessorSparseValues* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:

    AccessorSparseValues* _pObject;
    IntegerJsonHandler<int32_t> _bufferView;
    IntegerJsonHandler<int64_t> _byteOffset;
  };
}
