// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#include "AccessorSparseValuesJsonHandler.h"
#include "CesiumGltf/AccessorSparseValues.h"
#include <cassert>
#include <string>

using namespace CesiumGltf;

void AccessorSparseValuesJsonHandler::reset(JsonHandler* pParent, AccessorSparseValues* pObject) {
  ExtensibleObjectJsonHandler::reset(pParent);
  this->_pObject = pObject;
}

JsonHandler* AccessorSparseValuesJsonHandler::Key(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pObject);

  if ("bufferView"s == str) return property(this->_bufferView, this->_pObject->bufferView);
  if ("byteOffset"s == str) return property(this->_byteOffset, this->_pObject->byteOffset);

  return this->ExtensibleObjectKey(str, *this->_pObject);
}
