// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#include "AccessorSparseIndicesJsonHandler.h"
#include "CesiumGltf/AccessorSparseIndices.h"
#include <cassert>
#include <string>

using namespace CesiumGltf;

void AccessorSparseIndicesJsonHandler::reset(JsonHandler* pParent, AccessorSparseIndices* pObject) {
  ExtensibleObjectJsonHandler::reset(pParent);
  this->_pObject = pObject;
}

JsonHandler* AccessorSparseIndicesJsonHandler::Key(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pObject);

  if ("bufferView"s == str) return property(this->_bufferView, this->_pObject->bufferView);
  if ("byteOffset"s == str) return property(this->_byteOffset, this->_pObject->byteOffset);
  if ("componentType"s == str) return property(this->_componentType, this->_pObject->componentType);

  return this->ExtensibleObjectKey(str, *this->_pObject);
}
