// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "CesiumGltf/AnimationSampler.h"
#include "ExtensibleObjectJsonHandler.h"
#include "IntegerJsonHandler.h"

namespace CesiumGltf {
  struct AnimationSampler;

  class AnimationSamplerJsonHandler final : public ExtensibleObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, AnimationSampler* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:
    class InterpolationJsonHandler : public JsonHandler {
    public:
      void reset(JsonHandler* pParent, AnimationSampler::Interpolation* pEnum);
      virtual JsonHandler* String(const char* str, size_t length, bool copy) override;

    private:
      AnimationSampler::Interpolation* _pEnum = nullptr;
    };

    AnimationSampler* _pObject;
    IntegerJsonHandler<int32_t> _input;
    InterpolationJsonHandler _interpolation;
    IntegerJsonHandler<int32_t> _output;
  };
}
