// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#include "AnimationChannelTargetJsonHandler.h"
#include "CesiumGltf/AnimationChannelTarget.h"
#include <cassert>
#include <string>

using namespace CesiumGltf;

void AnimationChannelTargetJsonHandler::reset(JsonHandler* pParent, AnimationChannelTarget* pObject) {
  ExtensibleObjectJsonHandler::reset(pParent);
  this->_pObject = pObject;
}

JsonHandler* AnimationChannelTargetJsonHandler::Key(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pObject);

  if ("node"s == str) return property(this->_node, this->_pObject->node);
  if ("path"s == str) return property(this->_path, this->_pObject->path);

  return this->ExtensibleObjectKey(str, *this->_pObject);
}

void AnimationChannelTargetJsonHandler::PathJsonHandler::reset(JsonHandler* pParent, AnimationChannelTarget::Path* pEnum) {
  JsonHandler::reset(pParent);
  this->_pEnum = pEnum;
}

JsonHandler* AnimationChannelTargetJsonHandler::PathJsonHandler::String(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pEnum);

  if ("translation"s == str) *this->_pEnum = AnimationChannelTarget::Path::translation;
  else if ("rotation"s == str) *this->_pEnum = AnimationChannelTarget::Path::rotation;
  else if ("scale"s == str) *this->_pEnum = AnimationChannelTarget::Path::scale;
  else if ("weights"s == str) *this->_pEnum = AnimationChannelTarget::Path::weights;
  else return nullptr;

  return this->parent();
}
