// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#include "AnimationJsonHandler.h"
#include "CesiumGltf/Animation.h"
#include <cassert>
#include <string>

using namespace CesiumGltf;

void AnimationJsonHandler::reset(JsonHandler* pParent, Animation* pObject) {
  NamedObjectJsonHandler::reset(pParent);
  this->_pObject = pObject;
}

JsonHandler* AnimationJsonHandler::Key(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pObject);

  if ("channels"s == str) return property(this->_channels, this->_pObject->channels);
  if ("samplers"s == str) return property(this->_samplers, this->_pObject->samplers);

  return this->NamedObjectKey(str, *this->_pObject);
}
