// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "CesiumGltf/AnimationChannelTarget.h"
#include "ExtensibleObjectJsonHandler.h"
#include "IntegerJsonHandler.h"

namespace CesiumGltf {
  struct AnimationChannelTarget;

  class AnimationChannelTargetJsonHandler final : public ExtensibleObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, AnimationChannelTarget* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:
    class PathJsonHandler : public JsonHandler {
    public:
      void reset(JsonHandler* pParent, AnimationChannelTarget::Path* pEnum);
      virtual JsonHandler* String(const char* str, size_t length, bool copy) override;

    private:
      AnimationChannelTarget::Path* _pEnum = nullptr;
    };

    AnimationChannelTarget* _pObject;
    IntegerJsonHandler<int32_t> _node;
    PathJsonHandler _path;
  };
}
