// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "AnimationChannelJsonHandler.h"
#include "AnimationSamplerJsonHandler.h"
#include "ArrayJsonHandler.h"
#include "NamedObjectJsonHandler.h"

namespace CesiumGltf {
  struct Animation;

  class AnimationJsonHandler final : public NamedObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, Animation* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:

    Animation* _pObject;
    ArrayJsonHandler<AnimationChannel, AnimationChannelJsonHandler> _channels;
    ArrayJsonHandler<AnimationSampler, AnimationSamplerJsonHandler> _samplers;
  };
}
