// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#include "AnimationChannelJsonHandler.h"
#include "CesiumGltf/AnimationChannel.h"
#include <cassert>
#include <string>

using namespace CesiumGltf;

void AnimationChannelJsonHandler::reset(JsonHandler* pParent, AnimationChannel* pObject) {
  ExtensibleObjectJsonHandler::reset(pParent);
  this->_pObject = pObject;
}

JsonHandler* AnimationChannelJsonHandler::Key(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pObject);

  if ("sampler"s == str) return property(this->_sampler, this->_pObject->sampler);
  if ("target"s == str) return property(this->_target, this->_pObject->target);

  return this->ExtensibleObjectKey(str, *this->_pObject);
}
