// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "ExtensibleObjectJsonHandler.h"
#include "StringJsonHandler.h"

namespace CesiumGltf {
  struct Asset;

  class AssetJsonHandler final : public ExtensibleObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, Asset* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:

    Asset* _pObject;
    StringJsonHandler _copyright;
    StringJsonHandler _generator;
    StringJsonHandler _version;
    StringJsonHandler _minVersion;
  };
}
