// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "IntegerJsonHandler.h"
#include "NamedObjectJsonHandler.h"
#include "StringJsonHandler.h"

namespace CesiumGltf {
  struct Buffer;

  class BufferJsonHandler final : public NamedObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, Buffer* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:

    Buffer* _pObject;
    StringJsonHandler _uri;
    IntegerJsonHandler<int64_t> _byteLength;
  };
}
