// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "DoubleJsonHandler.h"
#include "ExtensibleObjectJsonHandler.h"

namespace CesiumGltf {
  struct CameraPerspective;

  class CameraPerspectiveJsonHandler final : public ExtensibleObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, CameraPerspective* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:

    CameraPerspective* _pObject;
    DoubleJsonHandler _aspectRatio;
    DoubleJsonHandler _yfov;
    DoubleJsonHandler _zfar;
    DoubleJsonHandler _znear;
  };
}
