// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "CameraOrthographicJsonHandler.h"
#include "CameraPerspectiveJsonHandler.h"
#include "CesiumGltf/Camera.h"
#include "NamedObjectJsonHandler.h"

namespace CesiumGltf {
  struct Camera;

  class CameraJsonHandler final : public NamedObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, Camera* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:
    class TypeJsonHandler : public JsonHandler {
    public:
      void reset(JsonHandler* pParent, Camera::Type* pEnum);
      virtual JsonHandler* String(const char* str, size_t length, bool copy) override;

    private:
      Camera::Type* _pEnum = nullptr;
    };

    Camera* _pObject;
    CameraOrthographicJsonHandler _orthographic;
    CameraPerspectiveJsonHandler _perspective;
    TypeJsonHandler _type;
  };
}
