// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "DoubleJsonHandler.h"
#include "ExtensibleObjectJsonHandler.h"

namespace CesiumGltf {
  struct CameraOrthographic;

  class CameraOrthographicJsonHandler final : public ExtensibleObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, CameraOrthographic* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:

    CameraOrthographic* _pObject;
    DoubleJsonHandler _xmag;
    DoubleJsonHandler _ymag;
    DoubleJsonHandler _zfar;
    DoubleJsonHandler _znear;
  };
}
