// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#include "CameraPerspectiveJsonHandler.h"
#include "CesiumGltf/CameraPerspective.h"
#include <cassert>
#include <string>

using namespace CesiumGltf;

void CameraPerspectiveJsonHandler::reset(JsonHandler* pParent, CameraPerspective* pObject) {
  ExtensibleObjectJsonHandler::reset(pParent);
  this->_pObject = pObject;
}

JsonHandler* CameraPerspectiveJsonHandler::Key(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pObject);

  if ("aspectRatio"s == str) return property(this->_aspectRatio, this->_pObject->aspectRatio);
  if ("yfov"s == str) return property(this->_yfov, this->_pObject->yfov);
  if ("zfar"s == str) return property(this->_zfar, this->_pObject->zfar);
  if ("znear"s == str) return property(this->_znear, this->_pObject->znear);

  return this->ExtensibleObjectKey(str, *this->_pObject);
}
