// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#include "ImageJsonHandler.h"
#include "CesiumGltf/Image.h"
#include <cassert>
#include <string>

using namespace CesiumGltf;

void ImageJsonHandler::reset(JsonHandler* pParent, Image* pObject) {
  NamedObjectJsonHandler::reset(pParent);
  this->_pObject = pObject;
}

JsonHandler* ImageJsonHandler::Key(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pObject);

  if ("uri"s == str) return property(this->_uri, this->_pObject->uri);
  if ("mimeType"s == str) return property(this->_mimeType, this->_pObject->mimeType);
  if ("bufferView"s == str) return property(this->_bufferView, this->_pObject->bufferView);

  return this->NamedObjectKey(str, *this->_pObject);
}

void ImageJsonHandler::MimeTypeJsonHandler::reset(JsonHandler* pParent, Image::MimeType* pEnum) {
  JsonHandler::reset(pParent);
  this->_pEnum = pEnum;
}

JsonHandler* ImageJsonHandler::MimeTypeJsonHandler::String(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pEnum);

  if ("image/jpeg"s == str) *this->_pEnum = Image::MimeType::image_jpeg;
  else if ("image/png"s == str) *this->_pEnum = Image::MimeType::image_png;
  else return nullptr;

  return this->parent();
}
