// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "CesiumGltf/Image.h"
#include "IntegerJsonHandler.h"
#include "NamedObjectJsonHandler.h"
#include "StringJsonHandler.h"

namespace CesiumGltf {
  struct Image;

  class ImageJsonHandler final : public NamedObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, Image* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:
    class MimeTypeJsonHandler : public JsonHandler {
    public:
      void reset(JsonHandler* pParent, Image::MimeType* pEnum);
      virtual JsonHandler* String(const char* str, size_t length, bool copy) override;

    private:
      Image::MimeType* _pEnum = nullptr;
    };

    Image* _pObject;
    StringJsonHandler _uri;
    MimeTypeJsonHandler _mimeType;
    IntegerJsonHandler<int32_t> _bufferView;
  };
}
