// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#include "MaterialOcclusionTextureInfoJsonHandler.h"
#include "CesiumGltf/MaterialOcclusionTextureInfo.h"
#include <cassert>
#include <string>

using namespace CesiumGltf;

void MaterialOcclusionTextureInfoJsonHandler::reset(JsonHandler* pParent, MaterialOcclusionTextureInfo* pObject) {
  ExtensibleObjectJsonHandler::reset(pParent);
  this->_pObject = pObject;
}

JsonHandler* MaterialOcclusionTextureInfoJsonHandler::Key(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pObject);

  if ("strength"s == str) return property(this->_strength, this->_pObject->strength);

  return this->ExtensibleObjectKey(str, *this->_pObject);
}
