// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#include "MaterialPBRMetallicRoughnessJsonHandler.h"
#include "CesiumGltf/MaterialPBRMetallicRoughness.h"
#include <cassert>
#include <string>

using namespace CesiumGltf;

void MaterialPBRMetallicRoughnessJsonHandler::reset(JsonHandler* pParent, MaterialPBRMetallicRoughness* pObject) {
  ExtensibleObjectJsonHandler::reset(pParent);
  this->_pObject = pObject;
}

JsonHandler* MaterialPBRMetallicRoughnessJsonHandler::Key(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pObject);

  if ("baseColorFactor"s == str) return property(this->_baseColorFactor, this->_pObject->baseColorFactor);
  if ("baseColorTexture"s == str) return property(this->_baseColorTexture, this->_pObject->baseColorTexture);
  if ("metallicFactor"s == str) return property(this->_metallicFactor, this->_pObject->metallicFactor);
  if ("roughnessFactor"s == str) return property(this->_roughnessFactor, this->_pObject->roughnessFactor);
  if ("metallicRoughnessTexture"s == str) return property(this->_metallicRoughnessTexture, this->_pObject->metallicRoughnessTexture);

  return this->ExtensibleObjectKey(str, *this->_pObject);
}
