// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#include "MaterialNormalTextureInfoJsonHandler.h"
#include "CesiumGltf/MaterialNormalTextureInfo.h"
#include <cassert>
#include <string>

using namespace CesiumGltf;

void MaterialNormalTextureInfoJsonHandler::reset(JsonHandler* pParent, MaterialNormalTextureInfo* pObject) {
  ExtensibleObjectJsonHandler::reset(pParent);
  this->_pObject = pObject;
}

JsonHandler* MaterialNormalTextureInfoJsonHandler::Key(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pObject);

  if ("scale"s == str) return property(this->_scale, this->_pObject->scale);

  return this->ExtensibleObjectKey(str, *this->_pObject);
}
