// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#include "MeshJsonHandler.h"
#include "CesiumGltf/Mesh.h"
#include <cassert>
#include <string>

using namespace CesiumGltf;

void MeshJsonHandler::reset(JsonHandler* pParent, Mesh* pObject) {
  NamedObjectJsonHandler::reset(pParent);
  this->_pObject = pObject;
}

JsonHandler* MeshJsonHandler::Key(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pObject);

  if ("primitives"s == str) return property(this->_primitives, this->_pObject->primitives);
  if ("weights"s == str) return property(this->_weights, this->_pObject->weights);

  return this->NamedObjectKey(str, *this->_pObject);
}
