// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "ArrayJsonHandler.h"
#include "DoubleJsonHandler.h"
#include "MeshPrimitiveJsonHandler.h"
#include "NamedObjectJsonHandler.h"

namespace CesiumGltf {
  struct Mesh;

  class MeshJsonHandler final : public NamedObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, Mesh* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:

    Mesh* _pObject;
    ArrayJsonHandler<MeshPrimitive, MeshPrimitiveJsonHandler> _primitives;
    ArrayJsonHandler<double, DoubleJsonHandler> _weights;
  };
}
