// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "ArrayJsonHandler.h"
#include "CesiumGltf/MeshPrimitive.h"
#include "DictionaryJsonHandler.h"
#include "ExtensibleObjectJsonHandler.h"
#include "IntegerJsonHandler.h"

namespace CesiumGltf {
  struct MeshPrimitive;

  class MeshPrimitiveJsonHandler final : public ExtensibleObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, MeshPrimitive* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:

    MeshPrimitive* _pObject;
    DictionaryJsonHandler<int32_t, IntegerJsonHandler<int32_t>> _attributes;
    IntegerJsonHandler<int32_t> _indices;
    IntegerJsonHandler<int32_t> _material;
    IntegerJsonHandler<MeshPrimitive::Mode> _mode;
    ArrayJsonHandler<std::unordered_map<std::string, int32_t>, DictionaryJsonHandler<int32_t, IntegerJsonHandler<int32_t>>> _targets;
  };
}
