// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "AccessorJsonHandler.h"
#include "AnimationJsonHandler.h"
#include "ArrayJsonHandler.h"
#include "AssetJsonHandler.h"
#include "BufferJsonHandler.h"
#include "BufferViewJsonHandler.h"
#include "CameraJsonHandler.h"
#include "ExtensibleObjectJsonHandler.h"
#include "ImageJsonHandler.h"
#include "IntegerJsonHandler.h"
#include "MaterialJsonHandler.h"
#include "MeshJsonHandler.h"
#include "NodeJsonHandler.h"
#include "SamplerJsonHandler.h"
#include "SceneJsonHandler.h"
#include "SkinJsonHandler.h"
#include "StringJsonHandler.h"
#include "TextureJsonHandler.h"

namespace CesiumGltf {
  struct Model;

  class ModelJsonHandler final : public ExtensibleObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, Model* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:

    Model* _pObject;
    ArrayJsonHandler<std::string, StringJsonHandler> _extensionsUsed;
    ArrayJsonHandler<std::string, StringJsonHandler> _extensionsRequired;
    ArrayJsonHandler<Accessor, AccessorJsonHandler> _accessors;
    ArrayJsonHandler<Animation, AnimationJsonHandler> _animations;
    AssetJsonHandler _asset;
    ArrayJsonHandler<Buffer, BufferJsonHandler> _buffers;
    ArrayJsonHandler<BufferView, BufferViewJsonHandler> _bufferViews;
    ArrayJsonHandler<Camera, CameraJsonHandler> _cameras;
    ArrayJsonHandler<Image, ImageJsonHandler> _images;
    ArrayJsonHandler<Material, MaterialJsonHandler> _materials;
    ArrayJsonHandler<Mesh, MeshJsonHandler> _meshes;
    ArrayJsonHandler<Node, NodeJsonHandler> _nodes;
    ArrayJsonHandler<Sampler, SamplerJsonHandler> _samplers;
    IntegerJsonHandler<int32_t> _scene;
    ArrayJsonHandler<Scene, SceneJsonHandler> _scenes;
    ArrayJsonHandler<Skin, SkinJsonHandler> _skins;
    ArrayJsonHandler<Texture, TextureJsonHandler> _textures;
  };
}
