// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "ArrayJsonHandler.h"
#include "DoubleJsonHandler.h"
#include "IntegerJsonHandler.h"
#include "NamedObjectJsonHandler.h"

namespace CesiumGltf {
  struct Node;

  class NodeJsonHandler final : public NamedObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, Node* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:

    Node* _pObject;
    IntegerJsonHandler<int32_t> _camera;
    ArrayJsonHandler<int32_t, IntegerJsonHandler<int32_t>> _children;
    IntegerJsonHandler<int32_t> _skin;
    ArrayJsonHandler<double, DoubleJsonHandler> _matrix;
    IntegerJsonHandler<int32_t> _mesh;
    ArrayJsonHandler<double, DoubleJsonHandler> _rotation;
    ArrayJsonHandler<double, DoubleJsonHandler> _scale;
    ArrayJsonHandler<double, DoubleJsonHandler> _translation;
    ArrayJsonHandler<double, DoubleJsonHandler> _weights;
  };
}
