// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#include "SamplerJsonHandler.h"
#include "CesiumGltf/Sampler.h"
#include <cassert>
#include <string>

using namespace CesiumGltf;

void SamplerJsonHandler::reset(JsonHandler* pParent, Sampler* pObject) {
  NamedObjectJsonHandler::reset(pParent);
  this->_pObject = pObject;
}

JsonHandler* SamplerJsonHandler::Key(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pObject);

  if ("magFilter"s == str) return property(this->_magFilter, this->_pObject->magFilter);
  if ("minFilter"s == str) return property(this->_minFilter, this->_pObject->minFilter);
  if ("wrapS"s == str) return property(this->_wrapS, this->_pObject->wrapS);
  if ("wrapT"s == str) return property(this->_wrapT, this->_pObject->wrapT);

  return this->NamedObjectKey(str, *this->_pObject);
}
