// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "CesiumGltf/Sampler.h"
#include "IntegerJsonHandler.h"
#include "NamedObjectJsonHandler.h"

namespace CesiumGltf {
  struct Sampler;

  class SamplerJsonHandler final : public NamedObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, Sampler* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:

    Sampler* _pObject;
    IntegerJsonHandler<Sampler::MagFilter> _magFilter;
    IntegerJsonHandler<Sampler::MinFilter> _minFilter;
    IntegerJsonHandler<Sampler::WrapS> _wrapS;
    IntegerJsonHandler<Sampler::WrapT> _wrapT;
  };
}
