// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#include "SceneJsonHandler.h"
#include "CesiumGltf/Scene.h"
#include <cassert>
#include <string>

using namespace CesiumGltf;

void SceneJsonHandler::reset(JsonHandler* pParent, Scene* pObject) {
  NamedObjectJsonHandler::reset(pParent);
  this->_pObject = pObject;
}

JsonHandler* SceneJsonHandler::Key(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pObject);

  if ("nodes"s == str) return property(this->_nodes, this->_pObject->nodes);

  return this->NamedObjectKey(str, *this->_pObject);
}
