// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#include "SkinJsonHandler.h"
#include "CesiumGltf/Skin.h"
#include <cassert>
#include <string>

using namespace CesiumGltf;

void SkinJsonHandler::reset(JsonHandler* pParent, Skin* pObject) {
  NamedObjectJsonHandler::reset(pParent);
  this->_pObject = pObject;
}

JsonHandler* SkinJsonHandler::Key(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pObject);

  if ("inverseBindMatrices"s == str) return property(this->_inverseBindMatrices, this->_pObject->inverseBindMatrices);
  if ("skeleton"s == str) return property(this->_skeleton, this->_pObject->skeleton);
  if ("joints"s == str) return property(this->_joints, this->_pObject->joints);

  return this->NamedObjectKey(str, *this->_pObject);
}
