// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#include "TextureJsonHandler.h"
#include "CesiumGltf/Texture.h"
#include <cassert>
#include <string>

using namespace CesiumGltf;

void TextureJsonHandler::reset(JsonHandler* pParent, Texture* pObject) {
  NamedObjectJsonHandler::reset(pParent);
  this->_pObject = pObject;
}

JsonHandler* TextureJsonHandler::Key(const char* str, size_t /*length*/, bool /*copy*/) {
  using namespace std::string_literals;

  assert(this->_pObject);

  if ("sampler"s == str) return property(this->_sampler, this->_pObject->sampler);
  if ("source"s == str) return property(this->_source, this->_pObject->source);

  return this->NamedObjectKey(str, *this->_pObject);
}
