// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "IntegerJsonHandler.h"
#include "NamedObjectJsonHandler.h"

namespace CesiumGltf {
  struct Texture;

  class TextureJsonHandler final : public NamedObjectJsonHandler {
  public:
    void reset(JsonHandler* pHandler, Texture* pObject);
    virtual JsonHandler* Key(const char* str, size_t length, bool copy) override;

  private:

    Texture* _pObject;
    IntegerJsonHandler<int32_t> _sampler;
    IntegerJsonHandler<int32_t> _source;
  };
}
