stateDiagram-v2
  unloaded : Unloaded
  contentLoading : Content Loading
  contentLoaded : Content Loaded
  done : Done
  failed : Failed
  failedTemp : Failed Temporarily
  unloading : Unloading
  [*] --> unloaded
  unloaded --> contentLoading: Start Async Loading
  contentLoading --> contentLoaded: Done Async Loading
  contentLoading --> failed: Load Failed
  contentLoading --> failedTemp: Retry Later
  failedTemp --> contentLoading: Start Async Loading
  contentLoaded --> done: Main Thread Loading
  contentLoaded --> unloaded: Unload Tile Content
  done --> unloading: Start Unloading
  unloading --> unloaded: Done Unloading
