---
config:
  layout: elk
title: Cesium3DTilesContent Dependency Graph
---
graph TD
  classDef dependencyNode fill:#fff,stroke:#ccc,color:#666
  classDef libraryNode fill:#9f9
  Cesium3DTilesContent[Cesium3DTilesContent] --> Cesium3DTiles[Cesium3DTiles]
  Cesium3DTilesContent[Cesium3DTilesContent] --> Cesium3DTilesReader[Cesium3DTilesReader]
  Cesium3DTilesContent[Cesium3DTilesContent] --> CesiumAsync[CesiumAsync]
  Cesium3DTilesContent[Cesium3DTilesContent] --> CesiumGeometry[CesiumGeometry]
  Cesium3DTilesContent[Cesium3DTilesContent] --> CesiumGeospatial[CesiumGeospatial]
  Cesium3DTilesContent[Cesium3DTilesContent] --> CesiumGltf[CesiumGltf]
  Cesium3DTilesContent[Cesium3DTilesContent] --> CesiumGltfContent[CesiumGltfContent]
  Cesium3DTilesContent[Cesium3DTilesContent] --> CesiumGltfReader[CesiumGltfReader]
  Cesium3DTilesContent[Cesium3DTilesContent] --> CesiumUtility[CesiumUtility]
  Cesium3DTilesContent[Cesium3DTilesContent] --> libmorton_libmorton{{libmorton::libmorton}}
  class libmorton_libmorton dependencyNode
  class Cesium3DTiles,Cesium3DTilesReader,CesiumAsync,CesiumGeometry,CesiumGeospatial,CesiumGltf,CesiumGltfContent,CesiumGltfReader,CesiumUtility,Cesium3DTilesContent libraryNode
  linkStyle 0 stroke:#ff0029,stroke-width:4px
  linkStyle 1 stroke:#377eb8,stroke-width:4px
  linkStyle 2 stroke:#66a61e,stroke-width:4px
  linkStyle 3 stroke:#984ea3,stroke-width:4px
  linkStyle 4 stroke:#00d2d5,stroke-width:4px
  linkStyle 5 stroke:#ff7f00,stroke-width:4px
  linkStyle 6 stroke:#af8d00,stroke-width:4px
  linkStyle 7 stroke:#7f80cd,stroke-width:4px
  linkStyle 8 stroke:#b3e900,stroke-width:4px
  linkStyle 9 stroke:#c42e60,stroke-width:4px
