---
config:
  layout: elk
title: CesiumJsonReader Dependency Graph
---
graph TD
  classDef dependencyNode fill:#fff,stroke:#ccc,color:#666
  classDef libraryNode fill:#9f9
  CesiumJsonReader[CesiumJsonReader] --> CesiumUtility[CesiumUtility]
  class CesiumUtility,CesiumJsonReader libraryNode
  linkStyle 0 stroke:#ff0029,stroke-width:4px
