// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "ReaderLibrary.h"

{{#each headers}}
#include {{this}}
{{/each}}

#define CODEGEN_API {{apiName}}_API

namespace {{namespace}} {

{{#each root.refs}}
{{> object }}
{{/each}}

} // {{namespace}}

#undef CODEGEN_API
