// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!

{{#each headers}}
#include {{this}}
{{/each}}

using namespace CesiumJsonReader;

namespace {{namespace}} {
{{#each root.refs}}
{{> object}}
{{/each}}
} // {{namespace}}
