// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "WriterLibrary.h"

{{#each headers}}
#include {{this}}
{{/each}}

namespace {{namespace}} {

{{#each root.refs}}
{{> object}}
{{/each}}

} // namespace {{namespace}}
