trigger: none
pr: none

parameters:
  - name: package-version
    type: string
  - name: linuxbuild
    displayName: Linux build
    type: boolean
    default: true
  # - name: windowsbuild
  #   type: boolean
  #   default: false

jobs:
  - job:
    displayName: Build cesium-native on Linux
    condition: eq('${{parameters.linuxbuild}}', true)
    pool:
      name: iModelTechLnxDeb11
      demands: "Agent.OS -equals Linux"
    steps:
      - checkout: self
        lfs: true
        submodules: recursive
        persistCredentials: true
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: "tools/cmake-linux.zip"
          destinationFolder: "tools"
          cleanDestinationFolder: false
      - script: chmod +x tools/cmake-linux/bin/cmake
      - script: tools/cmake-linux/bin/cmake -S $(Build.SourcesDirectory) -B $(Build.SourcesDirectory)/out -D CMAKE_C_COMPILER=/usr/lib/llvm-13/bin/clang -D CMAKE_CXX_COMPILER=/usr/lib/llvm-13/bin/clang++
      - script: tools/cmake-linux/bin/cmake --build $(Build.SourcesDirectory)/out --target CesiumGltfWriter --config Release
      - task: CopyFiles@2      
        displayName: 'Copy Cesium3DTiles include files to upack staging directory'
        inputs:
          SourceFolder: "Cesium3DTiles/include/Cesium3DTiles"
          Contents: "**"
          TargetFolder: upack-staging/include/Cesium3DTiles

      - task: CopyFiles@2
        displayName: 'Copy CesiumGltfWriter include files to upack staging directory'
        inputs:
          SourceFolder: "CesiumGltfWriter/include/CesiumGltfWriter"
          Contents: "**"
          TargetFolder: upack-staging/include/CesiumGltfWriter

      - task: CopyFiles@2
        displayName: 'Copy CesiumJsonWriter include files to upack staging directory'
        inputs:
          SourceFolder: "CesiumJsonWriter/include/CesiumJsonWriter"
          Contents: "**"
          TargetFolder: upack-staging/include/CesiumJsonWriter

      - task: CopyFiles@2
        displayName: 'Copy CesiumUtility include files to upack staging directory'
        inputs:
          SourceFolder: "CesiumUtility/include/CesiumUtility"
          Contents: "**"
          TargetFolder: upack-staging/include/CesiumUtility

      - task: CopyFiles@2
        displayName: 'Copy extern/glm include files to upack staging directory'
        inputs:
          SourceFolder: "extern/glm/glm"
          Contents: "**"
          TargetFolder: upack-staging/include/glm

      - task: CopyFiles@2
        displayName: 'Copy extern/gsl include files to upack staging directory'
        inputs:
          SourceFolder: "extern/GSL/include/gsl"
          Contents: "**"
          TargetFolder: upack-staging/include/gsl

      - task: CopyFiles@2
        displayName: 'Copy CesiumGltfWriter lib to upack staging directory'
        inputs:
          SourceFolder: "out/CesiumGltfWriter"
          Contents: "*.a"
          TargetFolder: upack-staging/lib

      - task: CopyFiles@2
        displayName: 'Copy CesiumJsonWriter lib to upack staging directory'
        inputs:
          SourceFolder: "out/CesiumJsonWriter"
          Contents: "*.a"
          TargetFolder: upack-staging/lib

      # - bash: ls -R upack-staging

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: upack-staging/lib
          artifactName: cesium-native_linux_x64

      # - task: UniversalPackages@0
      #   inputs:
      #   command: "publish"
      #   publishDirectory: "upack-staging"
      #   feedsToUsePublish: "internal"
      #   vstsFeedPublish: "upack"
      #   vstsFeedPackagePublish: "cesium_native_x64_linux"
      #   versionOption: "custom"
      #   versionPublish: $(package-version)
      #   env:
      #   AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

  # - job:
  #   displayName: Build cesium-native on Windows
  #   condition: eq('${{parameters.build-windows}}', true)
  #   pool:
  #     vmImage: "windows-latest"
  #   steps:
  #     - checkout: cesium-native
  #       lfs: true
  #       submodules: recursive
  #       persistCredentials: true

  #     - task: CMake@1
  #       inputs:
  #         cmakeArgs: -S $(Build.SourcesDirectory) -B $(Build.SourcesDirectory)/out -G "Visual Studio 16 2017 Win64"

  #     - task: CMake@1
  #       inputs:
  #         cmakeArgs: --build $(Build.SourcesDirectory)/out --target CesiumGltfWriter --config Release

  #     - task: CopyFiles@2
  #       inputs:
  #         SourceFolder: "Cesium3DTiles/include/Cesium3DTiles"
  #         Contents: "**"
  #         TargetFolder: upack-staging/include/Cesium3DTiles

  #     - task: CopyFiles@2
  #       inputs:
  #         SourceFolder: "CesiumGltfWriter/include/CesiumGltfWriter"
  #         Contents: "**"
  #         TargetFolder: upack-staging/include/CesiumGltfWriter

  #     - task: CopyFiles@2
  #       inputs:
  #         SourceFolder: "CesiumJsonWriter/include/CesiumJsonWriter"
  #         Contents: "**"
  #         TargetFolder: upack-staging/include/CesiumJsonWriter

  #     - task: CopyFiles@2
  #       inputs:
  #         SourceFolder: "CesiumUtility/include/CesiumUtility"
  #         Contents: "**"
  #         TargetFolder: upack-staging/include/CesiumUtility

  #     - task: CopyFiles@2
  #       inputs:
  #         SourceFolder: "extern/glm/glm"
  #         Contents: "**"
  #         TargetFolder: upack-staging/include/glm

  #     - task: CopyFiles@2
  #       inputs:
  #         SourceFolder: "extern/GSL/include/gsl"
  #         Contents: "**"
  #         TargetFolder: upack-staging/include/gsl

  #     - task: CopyFiles@2
  #       inputs:
  #         SourceFolder: "out/CesiumGltfWriter"
  #         Contents: "*.dll"
  #         TargetFolder: upack-staging/lib

  #     - task: CopyFiles@2
  #       inputs:
  #         SourceFolder: "out/CesiumJsonWriter"
  #         Contents: "*.dll"
  #         TargetFolder: upack-staging/lib

  # - task: PublishPipelineArtifact@1
  #   inputs:
  #     targetPath: upack-staging/lib
  #     artifactName: cesium-native_win_x64

  # - task: UniversalPackages@0
  #   inputs:
  #   command: "publish"
  #   publishDirectory: "upack-staging"
  #   feedsToUsePublish: "internal"
  #   vstsFeedPublish: "upack"
  #   vstsFeedPackagePublish: "cesium_native_x64_win"
  #   versionOption: "custom"
  #   versionPublish: $(package-version)
  #   env:
  #   AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
