# if (MSVC)
#     add_compile_options(/W4 /WX /wd4201 /bigobj)
# else()
#     add_compile_options(-Werror -Wall -Wextra -Wconversion -Wpedantic -Wshadow -Wsign-conversion)
# endif()

if(CESIUM_TARGET_WASM)
  add_compile_options(-sMEMORY64=1)
  add_link_options(-sMEMORY64=1 -sALLOW_MEMORY_GROWTH=1 -sMAXIMUM_MEMORY=8589934592)
endif()