// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "CesiumGltf/ExtensibleObject.h"
#include "CesiumGltf/Library.h"
#include <optional>
#include <string>

namespace CesiumGltf {
/**
 * @brief Metadata about the glTF asset.
 */
struct CESIUMGLTF_API Asset final : public ExtensibleObject {
  static inline constexpr const char* TypeName = "Asset";

  /**
   * @brief A copyright message suitable for display to credit the content
   * creator.
   */
  std::optional<std::string> copyright;

  /**
   * @brief Tool that generated this glTF model.  Useful for debugging.
   */
  std::optional<std::string> generator;

  /**
   * @brief The glTF version that this asset targets.
   */
  std::string version;

  /**
   * @brief The minimum glTF version that this asset targets.
   */
  std::optional<std::string> minVersion;
};
} // namespace CesiumGltf
