// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "CesiumGltf/NamedObject.h"
#include <cstdint>
#include <optional>
#include <string>

namespace CesiumGltf {
    /**
     * @brief A buffer points to binary geometry, animation, or skins.
     */
    struct BufferSpec : public NamedObject {

        /**
         * @brief The uri of the buffer.
         *
         * Relative paths are relative to the .gltf file.  Instead of referencing an external file, the uri can also be a data-uri.
         */
        std::optional<std::string> uri;

        /**
         * @brief The length of the buffer in bytes.
         */
        int64_t byteLength = int64_t();

    };
}
