// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "CesiumGltf/BufferCesium.h"
#include "CesiumGltf/NamedObject.h"
#include <cstdint>
#include <string>

namespace CesiumGltf {
    /**
     * @brief A buffer points to binary geometry, animation, or skins.
     */
    struct Buffer final : public NamedObject {

        /**
         * @brief The uri of the buffer.
         *
         * Relative paths are relative to the .gltf file.  Instead of referencing an external file, the uri can also be a data-uri.
         */
        std::string uri;

        /**
         * @brief The length of the buffer in bytes.
         */
        int64_t byteLength;

        /**
         * @brief Holds properties that are specific to the glTF loader rather than part of the glTF spec.
         */
        BufferCesium cesium;

    };
}
