// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "CesiumGltf/ExtensibleObject.h"

namespace CesiumGltf {
    /**
     * @brief An orthographic camera containing properties to create an orthographic projection matrix.
     */
    struct CameraOrthographic final : public ExtensibleObject {

        /**
         * @brief The floating-point horizontal magnification of the view. Must not be zero.
         */
        double xmag;

        /**
         * @brief The floating-point vertical magnification of the view. Must not be zero.
         */
        double ymag;

        /**
         * @brief The floating-point distance to the far clipping plane. `zfar` must be greater than `znear`.
         */
        double zfar;

        /**
         * @brief The floating-point distance to the near clipping plane.
         */
        double znear;
    };
}
