// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "EnumValue.h"
#include "Library.h"

#include <CesiumUtility/ExtensibleObject.h>

#include <optional>
#include <string>
#include <vector>

using namespace CesiumUtility;

namespace CesiumGltf {
/**
 * @brief An object defining the values of an enum.
 */
struct CESIUMGLTF_API Enum final : public ExtensibleObject {
  static inline constexpr const char* TypeName = "Enum";

  /**
   * @brief The name of the enum, e.g. for display purposes.
   */
  std::optional<std::string> name;

  /**
   * @brief The description of the enum.
   */
  std::optional<std::string> description;

  /**
   * @brief The type of the integer enum value.
   */
  std::string valueType = "UINT16";

  /**
   * @brief An array of enum values. Duplicate names or duplicate integer values
   * are not allowed.
   */
  std::vector<EnumValue> values;
};
} // namespace CesiumGltf
