// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "CesiumGltf/ExtensibleObject.h"
#include <cstdint>
#include <unordered_map>

namespace CesiumGltf {
    /**
     * @brief undefined
     */
    struct KHR_draco_mesh_compression : public ExtensibleObject {

        /**
         * @brief The index of the bufferView.
         */
        int32_t bufferView;

        /**
         * @brief A dictionary object, where each key corresponds to an attribute and its unique attribute id stored in the compressed geometry.
         */
        std::unordered_map<std::string, int32_t> attributes;

    };
}
