// This file was generated by generate-gltf-classes.
// DO NOT EDIT THIS FILE!
#pragma once

#include "CesiumGltf/ExtensibleObject.h"
#include "CesiumGltf/Library.h"
#include "CesiumGltf/TextureInfo.h"
#include <string>

namespace CesiumGltf {
/**
 * @brief A description of how to access property values from the color channels
 * of a texture.
 */
struct CESIUMGLTF_API TextureAccessor final : public ExtensibleObject {
  static inline constexpr const char* TypeName = "TextureAccessor";

  /**
   * @brief Texture channels containing property values. Channels are labeled by
   * `rgba` and are swizzled with a string of 1-4 characters.
   */
  std::string channels;

  /**
   * @brief The glTF texture and texture coordinates to use.
   */
  TextureInfo texture;
};
} // namespace CesiumGltf
