name: check-cla
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  CheckCLA:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: CesiumGS/github-actions/check-for-cla@check-for-cla-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-id: ${{ github.event.number }}
          microsoft-graph-info-json: ${{ secrets.MICROSOFT_GRAPH_INFO_JSON }}
          cla-url: https://cesium.com/learn/cesium-native/ref-doc/contributing.html#contributor-license-agreement-cla
          pull-request-guidelines-url: https://cesium.com/learn/cesium-native/ref-doc/contributing.html#opening-a-pull-request